config/routes.rb
PhotoApp::Application.routes.draw do

  resources :photos do
    resources :comments
  end

  devise_for :users

  get "home/index"

  root :to => 'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  attr_accessible :comment, :name
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :comments
  attr_accessible :description, :photo
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @photo = Photo.find(params[:photo_id])
    @comments = @photo.comments.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @photo, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @photo, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to @photo }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @photos = Photo.find(:all, :order => "id desc", :limit => 3)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    @comments = @photo.comments.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
    def create
      @photo = Photo.new(params[:photo])

      respond_to do |format|
        if @photo.save
          format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
          format.json { render json: @photo, status: :created, location: @photo }
        else
          format.html { render action: "new" }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
      end
    end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  def code_image
    @image_data = Photo.find(params[id])
    @image = @image_data.binary_data
    send_data(@image,:type => @image_data.content_type,
               :filename => @image_data.file_name,
               :disposition => 'inline')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/_form.html.erb
<%= form_for([@photo, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :rows => 4, :cols => 25 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Back', photo_comments_path(@photo) %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<p>
  <%= link_to "<< Back to Photo", photo_path(@photo) %>
</p>

<% @comments.each do |comment| %>
  <div>
    <b><%= comment.name %></b> said (<%= time_ago_in_words(comment.created_at) %> ago):<br/>
    <div class="lead"><%= comment.comment %></div>
    <div>
      <%= link_to 'Edit', edit_photo_comment_path(@photo, comment) %> | 
      <%= link_to 'Destroy', [@photo, comment], 
        method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
  <hr />
<% end %>

<%= link_to 'New Comment', new_photo_comment_path(@photo) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', photo_comments_path(@photo) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<%= link_to 'Back', photo_comments_path(@photo) %>

app/views/home/_authenticated.html.erb
<div class="center hero-unit">
  <h1>You are signed in!</h1>
  <h2>Share and comment on photos with the rest of the world!</h2>
  <div class="row">
    <% @photos.each do |photo| %>
      <div class="span3">
        <%= link_to image_tag(photo.photo_url(:thumb)), 
          photo_path(photo) %>
      </div>
    <% end %>

    <div class="offset1 span2 lead">
      <%= link_to "See all...", photos_path %>
    </div>

  </div>
</div>

app/views/home/_visitor.html.erb
<div class="center hero-unit">
  <h1>Welcome Guest!</h1>

  <h2>Share and comment on photos with the rest of the world!</h2>
  <div class="row">
    <% @photos.each do |photo| %>
      <div class="span3">
        <%= link_to image_tag(photo.photo_url(:thumb)), 
          photo_path(photo) %>
      </div>
    <% end %>

    <div class="offset1 span2 lead">
      <%= link_to "See all...", photos_path %>
    </div>

  </div>
</div>

<div class="row">

  <div class="span4">
    <h3>Already a Member?</h3>
    <%= render :partial => "layouts/sign_in_form" %>
  </div>

  <div class="span4">
    <h3>Itching to Join?</h3>
    <div>
    <%= link_to "Sign up now", 
      new_user_registration_path, 
      class: "btn btn-large btn-primary" %>
    </div>
  </div>

</div>

app/views/home/index.html.erb
<h1>Photo App Home Page</h1>
<% if signed_in? %>
  <%= render :partial => 'authenticated' %>
<% else %>
  <%= render :partial => 'visitor' %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"><script>
<![endif]-->

app/views/layouts/_sign_in_form.html.erb
<%= form_for("user", :url => user_session_path) do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, 
      :placeholder => "Email address",
      :autofocus => "autofocus" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password,
      :placeholder => "Password" %>
  </div>

  <div>
    <%= f.check_box :remember_me %> <%= f.label :remember_me %>
  </div>

  <div>
    <%= f.submit "Sign in" %> 
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo App</title>
  <%= render :partial => 'layouts/shim' %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div>
    <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Photo App", root_path, id: "logo", class: "brand" %>
        <div class="nav-collapse">
          <ul class="nav pull-right">
            <li><%= link_to "Photos", photos_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    </header>
  </div>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "#{name}" if msg.is_a?(String) %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>

  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label">Photo</label>
    <div class="controls">
      <%= f.file_field :photo %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :description, class: "text_field" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to "Cancel", photos_path, class: "btn" %>
  </div>

<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing Photos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Photo</th>
    </tr>
  </thead>
  <tbody>
  <% @photos.each do |photo| %>
    <tr>
      <td><%= link_to photo.description, photo_path(photo) %></td>
      <td><%= link_to image_tag(photo.photo_url(:thumb)), photo_path(photo) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />

<% if user_signed_in? %>
  <%= link_to 'New Photo', new_photo_path, class: 'btn' %>
<% end %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @photo.description %>
</h1>

<%= link_to '<< Back', photos_path %>

<% if signed_in? %>
  | <%= link_to 'Edit', edit_photo_path(@photo) %> |
  <%= link_to 'Delete', @photo, method: :delete, data: { confirm: 'Are you sure?' } %> 
<% end %>

<p>
  <%= image_tag @photo.photo_url if @photo.photo? %>
</p>

<% if signed_in? %>
  <h2 style="text-align: left;">Comments:</h2>
  <% @comments.each do |comment| %>
    <div>
      <b><%= comment.name %></b> said (<%= time_ago_in_words(comment.created_at) %> ago):
      <%= link_to 'Edit', edit_photo_comment_path(@photo, comment) %> | 
      <%= link_to 'Destroy', [@photo, comment], 
        method: :delete, data: { confirm: 'Are you sure?' } %>
      <div class="lead"><%= comment.comment %></div>
      <div>
      </div>
    </div>
    <hr />
  <% end %>
  <p>
  <%= link_to 'New Comment', new_photo_comment_path(@photo) %>
  </p>
<% end %>